### ISSUE TITLE
Support null safety

### ISSUE THREAD

**Issue by m0veax** [darioielardi/flutter_speed_dial#102]
Null safety is comming to flutter and dart and we should support it:

https://dart.dev/null-safety

Maybe we should create a branch where we can start working on it depending on the actual master.

Could you assign me the issue? I will try to get my hands on this in the next weeks. I actually need to understand the new concept anyway for my own apps and this would be a good starting point :)

**Comment by michalisioak** [comment]
I made a null safety version [here](https://github.com/michalisioak/flutter_speed_dial)
the example app worked, but I did not have anything else to try it on.

**Comment by prateekmedia** [comment]
> I made a null safety version [here](https://github.com/michalisioak/flutter_speed_dial)
> the example app worked, but I did not have anything else to try it on.

Looks great I think, you can create a pull request if you want to.

**Comment by m0veax** [comment]
I'll do a review :)

**Comment by prateekmedia** [comment]
DONE! Use the branch nullsafety(until merged in master) to get the benefits of it.
```
  flutter_speed_dial:
    git:
      url: git://github.com/darioielardi/flutter_speed_dial.git
      ref: nullsafety
```

**Comment by hpoul** [comment]
> DONE! Use the branch nullsafety(until merged in master) to get the benefits of it.

🥳

What is still missing before this can be merged? Why not at least push a prerelease version to pub, so people find it easier and try it?

**Comment by prateekmedia** [comment]
> > DONE! Use the branch nullsafety(until merged in master) to get the benefits of it.
> 
> 🥳
> 
> What is still missing before this can be merged? Why not at least push a prerelease version to pub, so people find it easier and try it?

I dont have access to pub.dev as @darioielardi has it and he pushes when he is free from his job, he hasn't even replied to my last two mails from february I dont know much about him so it may delay the release.

**Comment by m0veax** [comment]
Hey,

maybe @darioielardi could add you at least as uploader:

https://dart.dev/tools/pub/cmd/pub-uploader

`
$> dart pub uploader add bob@example.com
We have sent an invitation to bob@example.com, they will be added as uploader after they confirm it.
`

**Comment by prateekmedia** [comment]
> maybe @darioielardi could add you at least as uploader:
> 
> https://dart.dev/tools/pub/cmd/pub-uploader

I know but here are his words 

> Yes, I have the option to invite an “uploader” who would have admin rights on the package. Which is why I’d rather wait for a test period before doing that. I’m sure you can understand. I’d be glad to publish your work myself during that period.
>
> Dario Ielardi
``` on 31 Jan 2021, 7:23 pm ```

**Comment by nipunasudha** [comment]
Could anyone upload the null safe version to PUB or should we create a separate repository using the null safe branch?

**Comment by prateekmedia** [comment]
> Could anyone upload the null safe version to PUB or should we create a separate repository using the null safe branch?

What do you mean? Currently only @darioielardi have pub.dev rights so wait for him to respond, also you can try it anytime you want by using the git url in your pubspec.yaml file, It will be lot better for now.

**Comment by m0veax** [comment]
We should update the readme with a snippet regarding this.

I'm trying to submit it tommorow.

**Comment by m0veax** [comment]
Hi,

this should work until @darioielardi did a release

```
  flutter_speed_dial:
    git:
      url: https://github.com/darioielardi/flutter_speed_dial.git
      ref: nullsafety
```

**Comment by prateekmedia** [comment]
> Hi,
> 
> this should work until @darioielardi did a release
> 
> ```yaml
>   flutter_speed_dial:
>     git:
>       url: https://github.com/darioielardi/flutter_speed_dial.git
>       ref: master
> ```

nullsafety branch needs to be deleted so that some people doesnt miss the new commits, it would report error for them but it would help them to not have outdated code.

**Comment by kw2019ltd** [comment]
when creating PR?

**Comment by m0veax** [comment]
Hey, the PR was already created and merged into master. Just use above snippet in your pubspec until we were able to make a release.
