### ISSUE TITLE
SpeedDialChild not reactive when setting state in onTap

### ISSUE THREAD

**Issue by p0wl90** [darioielardi/flutter_speed_dial#181]
First of all, thank you for this great package! I use it in my app to apply filters to a list. Therefore, I change the icons and colors of the SpeedDialChildren to indicate whether a filter is active or not. In the most recent version, these changes are not applied until the speed dial is closed and reopened. See the below steps to reproduce the behaviour using your example. 

### Steps to Reproduce
* Use the example in this repository as a basis
* Change the ontap method of the first child to `onTap: () => setState(() => rmicons = !rmicons),`
* Start the Example
* Set Close Manually to True
* Open the FAB
* Click on the First Child

### Expected Behaviour
* The icon disappears after clicking 

### Actual Behaviour
* The icon does not change until the speed dial is closed and opened again

**Comment by Jollastro** [comment]
I'm also using the speed dial for the same purpose, is there any update about this problem?

**Comment by HeyShafty** [comment]
Was it working in a previous version?

**Comment by p0wl90** [comment]
Hey! Yes, it was working in a previous version. I investigated the bug a while but did not have the time to fix it. The issue seems to be that it is hard to propagate state changes to the "OverlayEntry" widget (but I just had a rough look!)

https://stackoverflow.com/questions/55386957/flutter-checkbox-doesnt-work-inside-overlayentry

**Comment by prateekmedia** [comment]
Hey @p0wl90, I have implemented the same code from above like the Stack of the OverlayEntry being in a seperate StatefulWidget. Please check and see if anything changes.

**Comment by p0wl90** [comment]
Thanks for tackling the issue. Sadly, it was not fixed (as visible in the GIF below). The icons should immediately disappear (while the menu is open) but they are still visible until the speed dial is reopened.

![untitled(1)](https://user-images.githubusercontent.com/6959020/145546400-184c749c-ef89-4e6e-99b6-e9c85c9e19c6.gif)

**Comment by antonbashir** [comment]
Hello everyone.
I have same issue. 

Steps:

1. Create SpeedDial with fixed children.
2. Open SpeedDial manually.
3. Do something in other widgets and notify SpeedDial  owner/parent.
4. Change the children during updating the parent widget.
5. Children have not been changed on screen.
6. After close - open manually I can see new children.

**Comment by luca-colazzo** [comment]
Working in version 6.0.0

Closing

**Comment by Jollastro** [comment]
It is not working yet.

What I'm doing is this:

```
SpeedDial(
    icon: Icons.filter_alt,
    closeManually: true,
    children: <SpeedDialChild>[
      SpeedDialChild(
        onTap: () => setState(() {
          _isEvoFiltered = !_isEvoFiltered;
        }),
        child: Icon(
          Icons.electrical_services,
          color: _isEvoFiltered ? Colors.red : null,
        ),
      ),
    ],
  ),
```

The icon color of the SpeedDialChild should change when I tap it.

The actual behavior is that the color changes only after closing the SpeedDial and reopening it.

**Comment by novvia-dev** [comment]
Also not working for me without closing the dial and re-opening it. @luca-colazzo recommend re-opening this?

**Comment by mradzinski** [comment]
Can confirm this is still not working on 7.0.0. @luca-colazzo maybe it's worth to re-open the issue?

**Comment by PenguinBIUBIUBIU** [comment]
> It is not working yet.
> 
> What I'm doing is this:
> 
> ```
> SpeedDial(
>     icon: Icons.filter_alt,
>     closeManually: true,
>     children: <SpeedDialChild>[
>       SpeedDialChild(
>         onTap: () => setState(() {
>           _isEvoFiltered = !_isEvoFiltered;
>         }),
>         child: Icon(
>           Icons.electrical_services,
>           color: _isEvoFiltered ? Colors.red : null,
>         ),
>       ),
>     ],
>   ),
> ```
> 
> The icon color of the SpeedDialChild should change when I tap it.
> 
> The actual behavior is that the color changes only after closing the SpeedDial and reopening it.

same with my project. 
version:  flutter_speed_dial: ^7.0.0
can you fix this please

**Comment by Lykeios1221** [comment]
For now, the workaround is directly triggering the rebuild on the child of SpeedDialChild, e.g.:
`
SpeedDialChild(
          child: Consumer<SettingsController>(
            builder: (context, controller, child) {
              return Icon(settingsController.actualThemeMode == ThemeMode.light
                  ? Icons.light_mode
                  : Icons.dark_mode);
            },
          ),
          onTap: () => onThemeChange(settingsController),
        )
`
This work for me to change icon without closing and reopen the dial.
(I'm still new to flutter, sorry if this is bad idea)
